"""Add unique constraint to restaurant name

Revision ID: d96a40c9bd47
Revises: d35e97484aef
Create Date: 2025-12-11 13:46:05.200354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd96a40c9bd47'
down_revision: Union[str, None] = 'd35e97484aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_unique_constraint(
        "uq_restaurant_name",
        "restaurants",
        ["name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   op.drop_constraint(
        "uq_restaurant_name",
        "restaurants",
        type_="unique"
   )
    # ### end Alembic commands ###
