"""Restaurant settings

Revision ID: c33fde117a87
Revises: 40e79799ab7a
Create Date: 2026-01-05 22:10:10.554306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c33fde117a87'
down_revision: Union[str, None] = '40e79799ab7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "restaurant_settings",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("restaurant_id", sa.Integer(), sa.ForeignKey("restaurants.id", ondelete="CASCADE"), unique=True, nullable=False),
        sa.Column("tax_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("service_charge", sa.Numeric(5, 2), nullable=True),
        sa.Column("auto_accept_orders", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("order_preparation_time", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('restaurant_settings')
    # ### end Alembic commands ###
