"""Seed global categories

Revision ID: 76db1aa9fa96
Revises: 54c1326d414d
Create Date: 2026-01-08 14:17:44.931043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '76db1aa9fa96'
down_revision: Union[str, None] = '54c1326d414d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    menu_categories = sa.table(
        "menu_categories",
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("display_order", sa.Integer),
        sa.column("is_active", sa.Boolean),
        sa.column("is_global", sa.Boolean),
        sa.column("restaurant_id", sa.Integer),
        sa.column("created_at", sa.DateTime),
        sa.column("updated_at", sa.DateTime),
    )

    now = datetime.utcnow()

    op.bulk_insert(
        menu_categories,
        [
            {
                "name": "North Indian",
                "description": "Popular North Indian dishes",
                "display_order": 1,
                "is_active": True,
                "is_global": True,
                "restaurant_id": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "South Indian",
                "description": "Traditional South Indian cuisine",
                "display_order": 2,
                "is_active": True,
                "is_global": True,
                "restaurant_id": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "Chinese",
                "description": "Chinese and Indo-Chinese dishes",
                "display_order": 3,
                "is_active": True,
                "is_global": True,
                "restaurant_id": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "Desserts",
                "description": "Sweets and desserts",
                "display_order": 4,
                "is_active": True,
                "is_global": True,
                "restaurant_id": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "name": "Beverages",
                "description": "Drinks and refreshments",
                "display_order": 5,
                "is_active": True,
                "is_global": True,
                "restaurant_id": None,
                "created_at": now,
                "updated_at": now,
            },
        ],
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM menu_categories
        WHERE is_global = true
        AND restaurant_id IS NULL
        AND name IN (
            'North Indian',
            'South Indian',
            'Chinese',
            'Desserts',
            'Beverages'
        )
        """
    )
    # ### end Alembic commands ###
