"""menu items

Revision ID: 809d0eae8d7c
Revises: 76db1aa9fa96
Create Date: 2026-01-08 14:42:44.068195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '809d0eae8d7c'
down_revision: Union[str, None] = '76db1aa9fa96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("restaurant_id", sa.Integer(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Numeric(10, 2), nullable=False),
        sa.Column("image_url", sa.String(length=512), nullable=True),
        sa.Column("is_available", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("is_vegetarian", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("is_global", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("preparation_time_minutes", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),

        sa.ForeignKeyConstraint(
            ["restaurant_id"],
            ["restaurants.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["menu_categories.id"],
            ondelete="CASCADE",
        ),
    )

    op.create_index("ix_menu_items_id", "menu_items", ["id"])
    op.create_index("ix_menu_items_name", "menu_items", ["name"])
    op.create_index("ix_menu_items_restaurant_id", "menu_items", ["restaurant_id"])
    op.create_index("ix_menu_items_category_id", "menu_items", ["category_id"])
    op.create_index(
        "ix_menu_items_restaurant_category",
        "menu_items",
        ["restaurant_id", "category_id"],
    )
    op.create_index(
        "ix_menu_items_availability",
        "menu_items",
        ["is_available"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_menu_items_availability", table_name="menu_items")
    op.drop_index("ix_menu_items_restaurant_category", table_name="menu_items")
    op.drop_index("ix_menu_items_category_id", table_name="menu_items")
    op.drop_index("ix_menu_items_restaurant_id", table_name="menu_items")
    op.drop_index("ix_menu_items_name", table_name="menu_items")
    op.drop_index("ix_menu_items_id", table_name="menu_items")
    op.drop_table("menu_items")
    # ### end Alembic commands ###
