"""updated the restaurant table for Restaurant admin role

Revision ID: 258f89b28c5e
Revises: ed741d331149
Create Date: 2026-01-05 08:42:47.459719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '258f89b28c5e'
down_revision: Union[str, None] = 'ed741d331149'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('business_hours', sa.JSON(), nullable=True))
    op.add_column('restaurants', sa.Column('description', sa.String(), nullable=True))
    op.add_column('restaurants', sa.Column('cuisine_type', sa.String(), nullable=True))
    
def downgrade() -> None:
    
    op.drop_column('restaurants', 'cuisine_type')
    op.drop_column('restaurants', 'description')
    op.drop_column('restaurants', 'business_hours')
    # ### end Alembic commands ###
