""" menu item variants

Revision ID: 8e1d942ad168
Revises: 0b26b4720191
Create Date: 2026-01-12 17:55:18.649092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e1d942ad168'
down_revision: Union[str, None] = '0b26b4720191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_item_variants",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "price_adjustment",
            sa.Numeric(10, 2),
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "is_default",
            sa.Boolean(),
            nullable=False,
            server_default="false",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),

        sa.ForeignKeyConstraint(
            ["item_id"],
            ["menu_items.id"],
            ondelete="CASCADE",
        ),
    )

    op.create_index(
        "ix_menu_item_variants_item_id",
        "menu_item_variants",
        ["item_id"],
    )

    op.create_index(
        "uq_menu_item_variants_item_name",
        "menu_item_variants",
        ["item_id", "name"],
        unique=True,
    )


    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_menu_item_variants_item_name",
        table_name="menu_item_variants",
    )
    op.drop_index(
        "ix_menu_item_variants_item_id",
        table_name="menu_item_variants",
    )
    op.drop_table("menu_item_variants")
    # ### end Alembic commands ###
