"""fix userrole enum to lowercase values

Revision ID: 65bfe937230c
Revises: 6a4dbd80b9cf
Create Date: 2026-01-26 13:06:30.267894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65bfe937230c'
down_revision: Union[str, None] = '6a4dbd80b9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE userrole_new AS ENUM (
            'admin',
            'restaurant_admin',
            'restaurant_staff'
        )
    """)

    # 2. Convert users.role safely
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE userrole_new
        USING LOWER(role::text)::userrole_new
    """)

    # 3. Drop old enum
    op.execute("DROP TYPE userrole")

    # 4. Rename new enum
    op.execute("ALTER TYPE userrole_new RENAME TO userrole")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE userrole_old AS ENUM (
            'ADMIN',
            'RESTAURANT_ADMIN',
            'RESTAURANT_STAFF'
        )
    """)
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE userrole_old
        USING UPPER(role::text)::userrole_old
    """)
    op.execute("DROP TYPE userrole")
    op.execute("ALTER TYPE userrole_old RENAME TO userrole")
    # ### end Alembic commands ###
