"""add time based availability to menu items

Revision ID: 6a4dbd80b9cf
Revises: 0a4dcbc0d885
Create Date: 2026-01-23 04:49:29.119759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a4dbd80b9cf'
down_revision: Union[str, None] = '0a4dcbc0d885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("menu_items",sa.Column("available_from", sa.Time(), nullable=True))
    op.add_column("menu_items", sa.Column("available_to", sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("menu_items", "available_to")
    op.drop_column("menu_items", "available_from")
    # ### end Alembic commands ###
